# Generated by Django 4.1.4 on 2023-01-03 15:08

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('prodId', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200, unique=True)),
                ('brand', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('uniqId', models.AutoField(primary_key=True, serialize=False)),
                ('retail_price', models.IntegerField()),
                ('discounted_price', models.IntegerField()),
                ('image', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), size=None)),
                ('description', models.CharField(max_length=60000)),
                ('rating', models.FloatField()),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productdata')),
            ],
        ),
    ]
