# Generated by Django 4.1.4 on 2023-01-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_image_productimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='productImage',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
