# Generated by Django 4.1.4 on 2023-01-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productimages_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='productImage',
            field=models.ImageField(upload_to='media'),
        ),
    ]
