# Generated by Django 4.1.4 on 2023-01-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_productimages_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimages',
            old_name='productImage',
            new_name='firstImage',
        ),
        migrations.AddField(
            model_name='productimages',
            name='secondImage',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='productimages',
            name='thirdImage',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
