# Generated by Django 4.1.4 on 2023-01-29 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='isStaff',
            new_name='is_staff',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='isSuperuser',
            new_name='is_superuser',
        ),
    ]
