# Generated by Django 4.1.4 on 2022-12-28 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pincode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='customers.address'),
        ),
    ]
