# Generated by Django 4.1.4 on 2023-01-03 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('street', models.CharField(max_length=200)),
                ('cart', models.JSONField()),
                ('date', models.DateField(auto_now_add=True)),
                ('promocode', models.CharField(max_length=50)),
                ('total', models.IntegerField()),
                ('delievered', models.BooleanField(default=False)),
                ('pincode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.address')),
            ],
        ),
    ]
